events:
  -
    name: "Adão"
    description_lines:
      - "Criação de Adão Gên. 2:7"
      - "Morte de Adão Gên. 5:5"
    tags:
      - Bible Character
    from:
      year: -4026
      month:
      day:
      precision: precise
    to:
      year: -3096
      month:
      day:
      precision: precise
  -
    name: "Enoque"
    tags:
      - Bible Character
    description_lines:
      - "Nascimento do justo Enoque Gên. 5:18"
      - "Transferência de Enoque; Gên. 5:23, 24; finda seu período de Judas 14 profetizar"
    from:
      year: -3404
      month:
      day:
      precision: precise
    to:
      year: -3039
      month:
      day:
      precision: precise
  -
    name: "Metusalém"
    tags:
      - Bible Character
    description_lines:
      - "Nascimento de Metusalém Gên. 5:21"
      - "Morte de Metusalém Gên. 5:27 Caem as águas do Dilúvio Gên. 7:6, 11 (outono, hem. norte)."
    from:
      year: -3339
      month:
      day:
      precision: precise
    to:
      year: -2370
      month:
      day:
      precision: precise
  -
    name: "Noé"
    tags:
      - Bible Character
    description_lines:
      - "Nascimento de Noé Gên. 5:28, 29"
      - "Morte de Noé Gên. 9:28, 29"
    from:
      year: -2970
      month:
      day:
      precision: precise
    to:
      year: -2020
      month:
      day:
      precision: precise
  -
    name: "Sem"
    tags:
      - Bible Character
    description_lines:
    - "Nascimento de Sem Gên. 7:11; Gên. 11:10"
    - "Morte de Sem Gên. 11:11"
    from:
      year: -2468
      month:
      day:
      precision: precise
    to:
      year: -1868
      month:
      day:
      precision: precise
  -
    name: "Abraão"
    tags:
      - Bible Character
    description_lines:
      - "Nascimento de Abraão Gên. 11:26, 32; Gên. 12:4"
      - "Morte de Abraão Gên. 25:7"
    from:
      year: -2018
      month:
      day:
      precision: precise
    to:
      year: -1843
      month:
      day:
      precision: precise
  -
    name: "Sara"
    tags:
      - Bible Character
    description_lines:
      - "10 anos mais nova que Abraão"
      - "Morte de Sara Gên. 17:17; Gên. 23:1"
    todos:
      - Confirmar data de nascimento
    from:
      year: -2008
      month:
      day:
      precision: about
    to:
      year: -1881
      month:
      day:
      precision: precise
  -
    name: "Davi"
    tags:
      - Bible Character
    description_lines:
      - "Nascimento de Davi em Belém 1 Sam. 16:1"
      - "Salomão sucede a Davi como 1 Reis 1:39; rei de Israel 1 Reis 2:12"
    todos:
      - "Verificar a data da morte de Davi"
    from:
      year: -1107
      month:
      day:
      precision: precise
    to:
      year: -1037
      month:
      day:
      precision: about
  -
    name: "Ismael"
    tags:
      - Bible Character
    description_lines:
      - "Nasce Ismael Gên. 16:15, 16"
      - "Morte de Ismael Gên. 25:17"
    from:
      year: -1932
      month:
      day:
      precision: precise
    to:
      year: -1795
      month:
      day:
      precision: precise
  -
    name: "Feito pacto da circuncisão Gên. 17:1,10, Julgamento de Sodoma e Gên. 17:24 Gomorra Gên. 19:24"
    from:
      year: -1919
      month:
      day:
      precision: precise
    to:
      year: -1919
      month:
      day:
      precision: precise
  -
    name: "Isaque"
    tags:
      - Bible Character
    description_lines:
      - "Nascimento de Isaque, o Gên. 21:2, 5; herdeiro legítimo; começo dos Atos 13:17-20 ‘cerca de 450 anos’"
      - "Morte de Isaque Gên. 35:28, 29"
    from:
      year: -1918
      month:
      day:
      precision: precise
    to:
      year: -1738
      month:
      day:
      precision: precise
  -
    name: "Jacó"
    tags:
      - Bible Character
    description_lines:
      - "Nascimento de Esaú e Jacó Gên. 25:26"
      - "Morte de Jacó Gên. 47:28"
    from:
      year: -1858
      month:
      day:
      precision: precise
    to:
      year: -1711
      month:
      day:
      precision: precise
  -
    name: "Moisés"
    tags:
      - Bible Character
    description_lines:
      - "Nascimento de Moisés Êxo. 2:2, 10"
      - "Moisés morre no Mte. Nebo, Deut. 34:1,5,7 em Moabe Israel entra em Canaã, sob Jos. 4:19 Josué"
    from:
      year: -1593
      month:
      day:
      precision: precise
    to:
      year: -1473
      month:
      day:
      precision: precise
