tags:
  - Kingdom
events:
  -
    name: "Davi Reina Judá"
    description_lines:
      - "Davi torna-se rei de Judá em Hébron 2 Sam. 2:4"
    from:
      year: -1077
      month:
      day:
      precision: precise
    to:
      year: -1070
      month:
      day:
      precision: precise
  -
    name: "Davi reina sobre todo o Israel"
    description_items:
      - "Davi torna-se rei sobre todo o Israel; faz de Jerusalém sua capital 2 Sam. 5:3-7"
      - "Salomão sucede a Davi como 1 Reis 1:39; rei de Israel 1 Reis 2:12"
    from:
      year: -1070
      month:
      day:
      precision: precise
    to:
      year: -1037
      month:
      day:
      precision: precise
  -
    name: "Roboão rei de Judá"
    description_items:
      - "Roboão sucede a Salomão; o 1 Reis 11:43; reino é dividido; Jeroboão 1 Reis 12:19 começa a reinar em Israel 1 Reis 12:20"
    from:
      year: -997
      month:
      day:
      precision: precise
    to:
      year: -980
      month:
      day:
      precision: precise
  -
    name: "Abijão (Abias) rei de Judá"
    description_items:
      - "Abijão (Abias) sucede a Roboão como rei de Judá 1 Reis 15:1, 2"
    from:
      year: -980
      month:
      day:
      precision: precise
    to:
      year: -977
      month:
      day:
      precision: precise
  -
    name: "Asa rei de Judá"
    description_lines:
      - "Asa sucede a Abijão como rei de Judá 1 Reis 15:9, 10"
    from:
      year: -977
      month:
      day:
      precision: precise
    to:
      year: -936
      month:
      day:
      precision: precise
  -
    name: "Jeosafá rei de Judá"
    description_lines:
      - "Jeosafá sucede a Asa como rei 1 Reis 22:41 de Judá 1 Reis 22:42"
    from:
      year: -936
      month:
      day:
      precision: precise
    to:
      year: -906
      month:
      day:
      precision: about
